<?xml version="1.0"?>
<package format="3">
  <name>care_description</name>
  <version>0.0.1</version>
  <description>Simple robot description with Gazebo sensors for Nav2 testing.</description>
  <maintainer email="charviagarwal2002@gmail.com">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>

  <exec_depend>gazebo_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/share" />
  </export>
</package>
