<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>care_navigation</name>
  <version>0.0.1</version>
  <description>CareBot Nav2 launch and configuration package</description>
  <maintainer email="user@todo.todo">User</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>nav2_bringup</depend>
  <depend>navigation2</depend>
  <depend>slam_toolbox</depend>
  <depend>teleop_twist_keyboard</depend>
  <depend>gazebo_ros</depend>
  <depend>rviz2</depend>
  <depend>robot_state_publisher</depend>
  <depend>care_description</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
